name: CI

on:
  push:
    branches:
      - main
    paths:
      - packages/**
      - scripts/sync-dockerhub-readme.mjs
      - .github/workflows/ci.yaml
      - .github/workflows/publish.yaml

concurrency:
  group: ${{ github.workflow }}-${{ github.ref_name }}
  cancel-in-progress: true

jobs:
  trigger:
    name: Publish Packages
    uses: ./.github/workflows/publish.yaml
    with:
      deploy-nitro-cli: true
      # Add more packages below as needed
      # deploy-foo: true
    secrets: inherit
